#LK6, silly sentences

print ("this is a madlib")

plu1= input("PLURAL NOUN:")
perin= input("LAST NAME OF A PERSON IN THE ROOM:")
agje1= input("ADJECTIVE:")
noun1= input("NOUN:")
noun2= input("NOUN:")
part1= input("PART OF BODY:")
part2= input("PART OF BODY:")
plu2= input("PLURAL NOUN:")
noun3= input("NOUN:")
noun4= input("NOUN:")
excl= input("EXCLAMATION!:")
noun5= input("NOUN:")
noun6= input("NOUN:")
noun7= input("NOUN:")
verb= input("VERB:")
noun8= input("NOUN:")
adje2= input("ADJECTIVE:")
noun9= input("NOUN:")
print ("a one-act play to performed by two "+plu1+" in this room. PATIENT: thank you for seeing me, Doctor "+perin+", on such "+adje2+" notice. DENTIST: what is your problem, young "+noun1+"? PATIENT: I have pain in my upper "+part1+", which is giving me a severe "+part2+" ache. DENTIST: Let me take a look. Open your "+noun2+" wide. Good. Now I'm going to tap your "+plu2+" with my "+noun3+". PATIENT: Shouldn't you give me a/an "+noun4+" Killer? DENTIST: it's not necesary yet. "+excl+"! I think I see a/an "+noun5+" in your upper "+noun6+". PATIENT: Are you going to pull my "+noun7+" out? DENTIST: No. I'm going to "+verb+" your tooth and put in a temporary "+noun8+". PATIENT: When do I come back for the "+adje2+" filling? DENTIST: A day I cash your "+noun9+".")